" Specify a directory for plugins.
" Avoid using standard Vim directory names like 'plugin'.
call plug#begin('~/.vim/plugged')


Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown'}
Plug 'romainl/Apprentice'
Plug 'junegunn/fzf.vim'


" Initialize plugin system
call plug#end()


set bg=dark

syntax on
filetype plugin indent on

set autoindent
set number
set relativenumber
set ruler
set incsearch
set hlsearch
